/**
 * Google Business Profile API Integration
 * Handles OAuth, account creation, and business profile management
 */

interface GoogleBusinessLocation {
  locationId: string;
  storeCode?: string;
  locationName: string;
  storefrontAddress: {
    addressLines: string[];
    locality: string;
    administrativeArea: string;
    postalCode: string;
    regionCode: string;
  };
  primaryPhone?: string;
  websiteUri?: string;
  categories?: {
    primaryCategory: {
      categoryId: string;
      displayName: string;
    };
  };
  storefrontCoordinates?: {
    latitude: number;
    longitude: number;
  };
}

interface GoogleBusinessHours {
  [day: string]: {
    open: string;
    close: string;
    closed?: boolean;
  };
}

/**
 * Get OAuth URL for Google Business Profile API
 */
export function getGoogleBusinessOAuthUrl(redirectUri: string, state?: string): string {
  const clientId = process.env.GOOGLE_BUSINESS_CLIENT_ID;
  const scopes = [
    'https://www.googleapis.com/auth/business.manage',
    'https://www.googleapis.com/auth/plus.business.manage',
  ].join(' ');

  if (!clientId) {
    throw new Error('GOOGLE_BUSINESS_CLIENT_ID not configured');
  }

  const params = new URLSearchParams({
    client_id: clientId,
    redirect_uri: redirectUri,
    response_type: 'code',
    scope: scopes,
    access_type: 'offline',
    prompt: 'consent',
    ...(state && { state }),
  });

  return `https://accounts.google.com/o/oauth2/v2/auth?${params.toString()}`;
}

/**
 * Exchange authorization code for access token
 */
export async function exchangeCodeForToken(
  code: string,
  redirectUri: string
): Promise<{ accessToken: string; refreshToken: string; expiresIn: number }> {
  const clientId = process.env.GOOGLE_BUSINESS_CLIENT_ID;
  const clientSecret = process.env.GOOGLE_BUSINESS_CLIENT_SECRET;

  if (!clientId || !clientSecret) {
    throw new Error('Google Business API credentials not configured');
  }

  const response = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: new URLSearchParams({
      code,
      client_id: clientId,
      client_secret: clientSecret,
      redirect_uri: redirectUri,
      grant_type: 'authorization_code',
    }),
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(`Token exchange failed: ${error.error_description || error.error}`);
  }

  const data = await response.json();
  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token,
    expiresIn: data.expires_in,
  };
}

/**
 * Refresh access token using refresh token
 */
export async function refreshAccessToken(
  refreshToken: string
): Promise<{ accessToken: string; expiresIn: number }> {
  const clientId = process.env.GOOGLE_BUSINESS_CLIENT_ID;
  const clientSecret = process.env.GOOGLE_BUSINESS_CLIENT_SECRET;

  if (!clientId || !clientSecret) {
    throw new Error('Google Business API credentials not configured');
  }

  const response = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: new URLSearchParams({
      refresh_token: refreshToken,
      client_id: clientId,
      client_secret: clientSecret,
      grant_type: 'refresh_token',
    }),
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(`Token refresh failed: ${error.error_description || error.error}`);
  }

  const data = await response.json();
  return {
    accessToken: data.access_token,
    expiresIn: data.expires_in,
  };
}

/**
 * Get list of locations for authenticated account
 */
export async function getLocations(accessToken: string): Promise<GoogleBusinessLocation[]> {
  const response = await fetch(
    'https://mybusinessaccountmanagement.googleapis.com/v1/accounts',
    {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    }
  );

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to fetch locations: ${error}`);
  }

  const data = await response.json();
  return data.accounts || [];
}

/**
 * Create a new Google Business Profile location
 */
export async function createLocation(
  accessToken: string,
  accountId: string,
  locationData: {
    name: string;
    address: string;
    phone: string;
    website?: string;
    category?: string;
    latitude?: number;
    longitude?: number;
  }
): Promise<{ locationId: string; placeId?: string }> {
  const location: GoogleBusinessLocation = {
    locationId: '', // Will be generated by Google
    locationName: locationData.name,
    storefrontAddress: {
      addressLines: locationData.address.split(',').map((line) => line.trim()),
      locality: '', // Extract from address
      administrativeArea: '', // Extract from address
      postalCode: '', // Extract from address
      regionCode: 'IN', // Default to India
    },
    primaryPhone: locationData.phone,
    websiteUri: locationData.website,
    categories: locationData.category
      ? {
          primaryCategory: {
            categoryId: locationData.category,
            displayName: locationData.category,
          },
        }
      : undefined,
    storefrontCoordinates:
      locationData.latitude && locationData.longitude
        ? {
            latitude: locationData.latitude,
            longitude: locationData.longitude,
          }
        : undefined,
  };

  const response = await fetch(
    `https://mybusinessaccountmanagement.googleapis.com/v1/accounts/${accountId}/locations`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(location),
    }
  );

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to create location: ${error}`);
  }

  const data = await response.json();
  return {
    locationId: data.name?.split('/').pop() || '',
    placeId: data.placeId,
  };
}

/**
 * Update business hours for a location
 */
export async function updateBusinessHours(
  accessToken: string,
  locationId: string,
  hours: GoogleBusinessHours
): Promise<void> {
  // This would use the Google Business Profile API v1
  // Implementation depends on specific API version
  const response = await fetch(
    `https://mybusiness.googleapis.com/v4/locations/${locationId}`,
    {
      method: 'PATCH',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        regularHours: hours,
      }),
    }
  );

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to update hours: ${error}`);
  }
}

/**
 * Get business profile data
 */
export async function getBusinessProfile(
  accessToken: string,
  locationId: string
): Promise<{
  rating?: number;
  reviewCount?: number;
  photos?: string[];
  hours?: GoogleBusinessHours;
}> {
  const response = await fetch(
    `https://mybusiness.googleapis.com/v4/locations/${locationId}`,
    {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    }
  );

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to fetch profile: ${error}`);
  }

  const data = await response.json();
  return {
    rating: data.rating,
    reviewCount: data.userRatingCount,
    photos: data.media?.photos?.map((p: any) => p.mediaItemUrl),
    hours: data.regularHours,
  };
}

/**
 * Verify if location is verified
 */
export async function checkVerificationStatus(
  accessToken: string,
  locationId: string
): Promise<{ verified: boolean; method?: string }> {
  const response = await fetch(
    `https://mybusiness.googleapis.com/v4/locations/${locationId}/verifications`,
    {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    }
  );

  if (!response.ok) {
    return { verified: false };
  }

  const data = await response.json();
  const verification = data.verifications?.[0];
  return {
    verified: verification?.state === 'VERIFIED',
    method: verification?.method,
  };
}

